export const GET_APPSTATE = 'GET_APPSTATE';
export const GET_APPSTATE_SUCCESS = 'GET_APPSTATE_SUCCESS';
export const GET_APPSTATE_FAILED = 'GET_APPSTATE_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const UPDATE_APPSTATE = 'UPDATE_APPSTATE';
export const CHANGE_APP_LANGUAGE = 'CHANGE_APP_LANGUAGE';